Another bugfix for the `Statement.getGeneratedKeys()` which required `Statement.RETURN_GENERATED_KEYS` on `Statement.execute()`.
The following error was shown in the logs: 
{{{
java.sql.SQLException: Generated keys not requested. You need to specify Statement.RETURN_GENERATED_KEYS to Statement.executeUpdate() or Connection.prepareStatement().
}}}

git-svn-id: http://www.twcore.org/svn/trunk@3543 9f8b3893-2a26-0410-9d00-a71e40fd2f77